# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yigit Sen"
resume_title:                   "Student"
resume_contact_email:           "yigit@yigitsen.me"
resume_contact_telephone:       "+90 542 746 3379"
resume_contact_address:         "87 Kurucesme Street, 34345, Istanbul, TURKEY"
resume_header_contact_info: "87 Kurucesme Street, Istanbuk | +90 542 746 3379 | yigit@yigitsen"
resume_header_intro: "<p> Student in American Robert College of Istanbul, President of RC Makers, RC ROV Team and RC Ushers' Corp. Electronics enthusiast, violinist. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/senyig20/resume-template"
  resume_twitter_url:           "http://twitter.com/senyig20"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yi%C4%9Fit-%C5%9Fen-8b1a97107/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "yigitsen.me"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
